name: Coverage
on: [push, pull_request]

jobs:
  build:
    name: Coverage ${{ matrix.buildsystem }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        buildsystem: [cmake]
        os: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Prepare
        run: .github/scripts/run-prepare ${{ matrix.buildsystem }} ${{ matrix.os }}
      - name: Test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
        run: .github/scripts/run-cmake-coverage
